"""initial schema

Revision ID: ed5e80f54e32
Revises: 
Create Date: 2026-08-26 09:57:58.160730
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'ed5e80f54e32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('actor', sa.String(length=48), nullable=False),
    sa.Column('action', sa.String(length=96), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_at'), ['at'], unique=False)

    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('model_version', sa.String(length=24), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('holdout_start', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('by_bucket', sa.JSON(), nullable=False),
    sa.Column('calibration', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fx_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_ccy', sa.String(length=8), nullable=False),
    sa.Column('quote_ccy', sa.String(length=8), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fx_rates', schema=None) as batch_op:
        batch_op.create_index('ix_fx_pair_date', ['base_ccy', 'quote_ccy', 'rate_date'], unique=True)

    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=24), nullable=False),
    sa.Column('exchange', sa.String(length=16), nullable=False),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('sector', sa.String(length=64), nullable=False),
    sa.Column('industry', sa.String(length=96), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('security_type', sa.String(length=16), nullable=False),
    sa.Column('is_shell', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('listed_at', sa.Date(), nullable=True),
    sa.Column('delisted_at', sa.Date(), nullable=True),
    sa.Column('delisting_reason', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instruments_market'), ['market'], unique=False)
        batch_op.create_index(batch_op.f('ix_instruments_sector'), ['sector'], unique=False)
        batch_op.create_index(batch_op.f('ix_instruments_ticker'), ['ticker'], unique=False)
        batch_op.create_index('ix_instruments_ticker_exchange', ['ticker', 'exchange'], unique=True)

    op.create_table('job_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=48), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_runs_job_name'), ['job_name'], unique=False)

    op.create_table('macro_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.String(length=48), nullable=False),
    sa.Column('obs_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('macro_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_macro_observations_series_id'), ['series_id'], unique=False)
        batch_op.create_index('ix_macro_series_obs', ['series_id', 'obs_date'], unique=True)
        batch_op.create_index('ix_macro_series_pub', ['series_id', 'published_at'], unique=False)

    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('weights', sa.JSON(), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('formula_hash', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('provider_health',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('capability', sa.String(length=24), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('configured', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('message', sa.String(length=400), nullable=False),
    sa.Column('staleness_days', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_health', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_health_provider'), ['provider'], unique=False)

    op.create_table('raw_payloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('endpoint', sa.String(length=200), nullable=False),
    sa.Column('params_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_payloads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_payloads_provider'), ['provider'], unique=False)
        batch_op.create_index('ix_raw_provider_hash', ['provider', 'params_hash'], unique=False)

    op.create_table('score_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('model_version', sa.String(length=24), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('trigger', sa.String(length=24), nullable=False),
    sa.Column('universe_size', sa.Integer(), nullable=False),
    sa.Column('scored', sa.Integer(), nullable=False),
    sa.Column('abstained', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('score_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_score_runs_as_of'), ['as_of'], unique=False)

    op.create_table('backtest_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('family', sa.String(length=32), nullable=False),
    sa.Column('horizon', sa.String(length=8), nullable=False),
    sa.Column('signal_date', sa.Date(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=48), nullable=False),
    sa.Column('holding_days', sa.Integer(), nullable=True),
    sa.Column('return_pct', sa.Float(), nullable=True),
    sa.Column('benchmark_return_pct', sa.Float(), nullable=True),
    sa.Column('mae_pct', sa.Float(), nullable=True),
    sa.Column('mfe_pct', sa.Float(), nullable=True),
    sa.Column('costs_bps', sa.Float(), nullable=True),
    sa.Column('opportunity', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('risk', sa.Float(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backtest_trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backtest_trades_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_backtest_trades_run_id'), ['run_id'], unique=False)
        batch_op.create_index('ix_bt_trade_run_instr', ['run_id', 'instrument_id'], unique=False)

    op.create_table('catalysts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=False),
    sa.Column('date_confirmed', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=False),
    sa.Column('binary', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('outcome', sa.String(length=400), nullable=True),
    sa.Column('outcome_date', sa.Date(), nullable=True),
    sa.Column('url', sa.String(length=400), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('catalysts', schema=None) as batch_op:
        batch_op.create_index('ix_catalyst_dedup', ['instrument_id', 'external_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_catalysts_expected_date'), ['expected_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalysts_instrument_id'), ['instrument_id'], unique=False)

    op.create_table('corporate_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('factor', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('detail', sa.String(length=240), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('corporate_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_corporate_actions_ex_date'), ['ex_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_corporate_actions_instrument_id'), ['instrument_id'], unique=False)

    op.create_table('engine_outputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('engine', sa.String(length=24), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('data_quality', sa.Float(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['score_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('engine_outputs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engine_outputs_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_engine_outputs_run_id'), ['run_id'], unique=False)
        batch_op.create_index('ix_engine_run_instr', ['run_id', 'instrument_id', 'engine'], unique=True)

    op.create_table('estimate_snaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('metric', sa.String(length=12), nullable=False),
    sa.Column('fiscal_label', sa.String(length=16), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('mean', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('analyst_count', sa.Integer(), nullable=False),
    sa.Column('mean_30d_ago', sa.Float(), nullable=True),
    sa.Column('mean_90d_ago', sa.Float(), nullable=True),
    sa.Column('up_revisions_30d', sa.Integer(), nullable=False),
    sa.Column('down_revisions_30d', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('estimate_snaps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_estimate_snaps_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index('ix_estimates_pit', ['instrument_id', 'as_of', 'metric', 'fiscal_label'], unique=False)

    op.create_table('fundamental_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('period_type', sa.String(length=2), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('is_restatement', sa.Boolean(), nullable=False),
    sa.Column('restates_period_end', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('source_reference', sa.String(length=300), nullable=False),
    sa.Column('raw_payload_id', sa.Integer(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['raw_payload_id'], ['raw_payloads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fundamental_reports', schema=None) as batch_op:
        batch_op.create_index('ix_fund_pit', ['instrument_id', 'published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_fundamental_reports_instrument_id'), ['instrument_id'], unique=False)

    op.create_table('insider_txs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('filed_at', sa.DateTime(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('insider_name', sa.String(length=120), nullable=False),
    sa.Column('insider_role', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('url', sa.String(length=400), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insider_txs', schema=None) as batch_op:
        batch_op.create_index('ix_insider_pit', ['instrument_id', 'filed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_insider_txs_instrument_id'), ['instrument_id'], unique=False)

    op.create_table('news_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('headline', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source_name', sa.String(length=80), nullable=False),
    sa.Column('source_type', sa.String(length=24), nullable=False),
    sa.Column('url', sa.String(length=400), nullable=False),
    sa.Column('sentiment', sa.Float(), nullable=False),
    sa.Column('novelty', sa.Float(), nullable=False),
    sa.Column('duplicate_of', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_of'], ['news_items.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.create_index('ix_news_dedup', ['instrument_id', 'external_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_news_items_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_items_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_items_published_at'), ['published_at'], unique=False)

    op.create_table('portfolio_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('avg_cost_local', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('opened_at', sa.Date(), nullable=False),
    sa.Column('closed_at', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_positions_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_positions_instrument_id'), ['instrument_id'], unique=False)

    op.create_table('price_bars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('bar_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_bars', schema=None) as batch_op:
        batch_op.create_index('ix_price_bars_instrument_date', ['instrument_id', 'bar_date'], unique=True)
        batch_op.create_index(batch_op.f('ix_price_bars_instrument_id'), ['instrument_id'], unique=False)

    op.create_table('score_bundles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('model_version', sa.String(length=24), nullable=False),
    sa.Column('best_fit_horizon', sa.String(length=8), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['score_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('score_bundles', schema=None) as batch_op:
        batch_op.create_index('ix_bundle_run_instr', ['run_id', 'instrument_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_score_bundles_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_bundles_run_id'), ['run_id'], unique=False)

    op.create_table('shares_outstanding_obs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shares_outstanding_obs', schema=None) as batch_op:
        batch_op.create_index('ix_shares_obs_pit', ['instrument_id', 'published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_shares_outstanding_obs_instrument_id'), ['instrument_id'], unique=False)

    op.create_table('short_interest_obs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('shares_short', sa.Float(), nullable=False),
    sa.Column('pct_float', sa.Float(), nullable=True),
    sa.Column('days_to_cover', sa.Float(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('short_interest_obs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_short_interest_obs_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index('ix_short_pit', ['instrument_id', 'published_at'], unique=False)

    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('family', sa.String(length=32), nullable=False),
    sa.Column('horizon', sa.String(length=8), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('first_run_id', sa.Integer(), nullable=False),
    sa.Column('last_run_id', sa.Integer(), nullable=False),
    sa.Column('anchor_price', sa.Float(), nullable=True),
    sa.Column('anchor_date', sa.Date(), nullable=True),
    sa.Column('entry_plan', sa.JSON(), nullable=False),
    sa.Column('last_scores', sa.JSON(), nullable=False),
    sa.Column('last_alert_at', sa.DateTime(), nullable=True),
    sa.Column('last_alert_opportunity', sa.Float(), nullable=True),
    sa.Column('last_alert_risk', sa.Float(), nullable=True),
    sa.Column('last_alert_price', sa.Float(), nullable=True),
    sa.Column('state_history', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['first_run_id'], ['score_runs.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['last_run_id'], ['score_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index('ix_signal_identity', ['instrument_id', 'family', 'horizon', 'active'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_family'), ['family'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_state'), ['state'], unique=False)

    op.create_table('target_snaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('mean', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('std', sa.Float(), nullable=True),
    sa.Column('analyst_count', sa.Integer(), nullable=False),
    sa.Column('median_age_days', sa.Float(), nullable=True),
    sa.Column('mean_30d_ago', sa.Float(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('target_snaps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_target_snaps_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index('ix_targets_pit', ['instrument_id', 'as_of'], unique=False)

    op.create_table('ticker_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('old_ticker', sa.String(length=24), nullable=False),
    sa.Column('new_ticker', sa.String(length=24), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticker_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticker_changes_instrument_id'), ['instrument_id'], unique=False)

    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlist_items_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_watchlist_items_instrument_id'), ['instrument_id'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('family', sa.String(length=32), nullable=False),
    sa.Column('lifecycle_state', sa.String(length=16), nullable=False),
    sa.Column('transition', sa.String(length=48), nullable=False),
    sa.Column('horizon', sa.String(length=8), nullable=False),
    sa.Column('priority', sa.String(length=8), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('narrative_source', sa.String(length=16), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('delivered', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['score_runs.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_signal_id'), ['signal_id'], unique=False)

    op.create_table('score_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('bundle_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('horizon', sa.String(length=8), nullable=False),
    sa.Column('opportunity', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('risk', sa.Float(), nullable=False),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('abstained', sa.Boolean(), nullable=False),
    sa.Column('abstain_reasons', sa.JSON(), nullable=False),
    sa.Column('gate', sa.JSON(), nullable=True),
    sa.Column('explanation', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['bundle_id'], ['score_bundles.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['score_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('score_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_score_records_as_of'), ['as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_records_bundle_id'), ['bundle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_records_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_records_run_id'), ['run_id'], unique=False)
        batch_op.create_index('ix_score_run_instr_h', ['run_id', 'instrument_id', 'horizon'], unique=True)

    op.create_table('alert_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_notes_alert_id'), ['alert_id'], unique=False)

    op.create_table('notification_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.String(length=32), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.String(length=400), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_deliveries_alert_id'), ['alert_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_deliveries_alert_id'))

    op.drop_table('notification_deliveries')
    with op.batch_alter_table('alert_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_notes_alert_id'))

    op.drop_table('alert_notes')
    with op.batch_alter_table('score_records', schema=None) as batch_op:
        batch_op.drop_index('ix_score_run_instr_h')
        batch_op.drop_index(batch_op.f('ix_score_records_run_id'))
        batch_op.drop_index(batch_op.f('ix_score_records_instrument_id'))
        batch_op.drop_index(batch_op.f('ix_score_records_bundle_id'))
        batch_op.drop_index(batch_op.f('ix_score_records_as_of'))

    op.drop_table('score_records')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_signal_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_run_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_instrument_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_created_at'))

    op.drop_table('alerts')
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlist_items_instrument_id'))
        batch_op.drop_index(batch_op.f('ix_watchlist_items_active'))

    op.drop_table('watchlist_items')
    with op.batch_alter_table('ticker_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticker_changes_instrument_id'))

    op.drop_table('ticker_changes')
    with op.batch_alter_table('target_snaps', schema=None) as batch_op:
        batch_op.drop_index('ix_targets_pit')
        batch_op.drop_index(batch_op.f('ix_target_snaps_instrument_id'))

    op.drop_table('target_snaps')
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_state'))
        batch_op.drop_index(batch_op.f('ix_signals_instrument_id'))
        batch_op.drop_index(batch_op.f('ix_signals_family'))
        batch_op.drop_index(batch_op.f('ix_signals_active'))
        batch_op.drop_index('ix_signal_identity')

    op.drop_table('signals')
    with op.batch_alter_table('short_interest_obs', schema=None) as batch_op:
        batch_op.drop_index('ix_short_pit')
        batch_op.drop_index(batch_op.f('ix_short_interest_obs_instrument_id'))

    op.drop_table('short_interest_obs')
    with op.batch_alter_table('shares_outstanding_obs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shares_outstanding_obs_instrument_id'))
        batch_op.drop_index('ix_shares_obs_pit')

    op.drop_table('shares_outstanding_obs')
    with op.batch_alter_table('score_bundles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_score_bundles_run_id'))
        batch_op.drop_index(batch_op.f('ix_score_bundles_instrument_id'))
        batch_op.drop_index('ix_bundle_run_instr')

    op.drop_table('score_bundles')
    with op.batch_alter_table('price_bars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_bars_instrument_id'))
        batch_op.drop_index('ix_price_bars_instrument_date')

    op.drop_table('price_bars')
    with op.batch_alter_table('portfolio_positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_positions_instrument_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_positions_active'))

    op.drop_table('portfolio_positions')
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_items_published_at'))
        batch_op.drop_index(batch_op.f('ix_news_items_instrument_id'))
        batch_op.drop_index(batch_op.f('ix_news_items_external_id'))
        batch_op.drop_index('ix_news_dedup')

    op.drop_table('news_items')
    with op.batch_alter_table('insider_txs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insider_txs_instrument_id'))
        batch_op.drop_index('ix_insider_pit')

    op.drop_table('insider_txs')
    with op.batch_alter_table('fundamental_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fundamental_reports_instrument_id'))
        batch_op.drop_index('ix_fund_pit')

    op.drop_table('fundamental_reports')
    with op.batch_alter_table('estimate_snaps', schema=None) as batch_op:
        batch_op.drop_index('ix_estimates_pit')
        batch_op.drop_index(batch_op.f('ix_estimate_snaps_instrument_id'))

    op.drop_table('estimate_snaps')
    with op.batch_alter_table('engine_outputs', schema=None) as batch_op:
        batch_op.drop_index('ix_engine_run_instr')
        batch_op.drop_index(batch_op.f('ix_engine_outputs_run_id'))
        batch_op.drop_index(batch_op.f('ix_engine_outputs_instrument_id'))

    op.drop_table('engine_outputs')
    with op.batch_alter_table('corporate_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corporate_actions_instrument_id'))
        batch_op.drop_index(batch_op.f('ix_corporate_actions_ex_date'))

    op.drop_table('corporate_actions')
    with op.batch_alter_table('catalysts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalysts_instrument_id'))
        batch_op.drop_index(batch_op.f('ix_catalysts_expected_date'))
        batch_op.drop_index('ix_catalyst_dedup')

    op.drop_table('catalysts')
    with op.batch_alter_table('backtest_trades', schema=None) as batch_op:
        batch_op.drop_index('ix_bt_trade_run_instr')
        batch_op.drop_index(batch_op.f('ix_backtest_trades_run_id'))
        batch_op.drop_index(batch_op.f('ix_backtest_trades_instrument_id'))

    op.drop_table('backtest_trades')
    with op.batch_alter_table('score_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_score_runs_as_of'))

    op.drop_table('score_runs')
    with op.batch_alter_table('raw_payloads', schema=None) as batch_op:
        batch_op.drop_index('ix_raw_provider_hash')
        batch_op.drop_index(batch_op.f('ix_raw_payloads_provider'))

    op.drop_table('raw_payloads')
    with op.batch_alter_table('provider_health', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_health_provider'))

    op.drop_table('provider_health')
    op.drop_table('model_versions')
    with op.batch_alter_table('macro_observations', schema=None) as batch_op:
        batch_op.drop_index('ix_macro_series_pub')
        batch_op.drop_index('ix_macro_series_obs')
        batch_op.drop_index(batch_op.f('ix_macro_observations_series_id'))

    op.drop_table('macro_observations')
    with op.batch_alter_table('job_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_runs_job_name'))

    op.drop_table('job_runs')
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.drop_index('ix_instruments_ticker_exchange')
        batch_op.drop_index(batch_op.f('ix_instruments_ticker'))
        batch_op.drop_index(batch_op.f('ix_instruments_sector'))
        batch_op.drop_index(batch_op.f('ix_instruments_market'))

    op.drop_table('instruments')
    with op.batch_alter_table('fx_rates', schema=None) as batch_op:
        batch_op.drop_index('ix_fx_pair_date')

    op.drop_table('fx_rates')
    op.drop_table('backtest_runs')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_at'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
